require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BrewhousesController do

  # This should return the minimal set of attributes required to create a valid
  # Brewhouse. As you add validations to Brewhouse, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BrewhousesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all brewhouses as @brewhouses" do
      brewhouse = Brewhouse.create! valid_attributes
      get :index, {}, valid_session
      assigns(:brewhouses).should eq([brewhouse])
    end
  end

  describe "GET show" do
    it "assigns the requested brewhouse as @brewhouse" do
      brewhouse = Brewhouse.create! valid_attributes
      get :show, {:id => brewhouse.to_param}, valid_session
      assigns(:brewhouse).should eq(brewhouse)
    end
  end

  describe "GET new" do
    it "assigns a new brewhouse as @brewhouse" do
      get :new, {}, valid_session
      assigns(:brewhouse).should be_a_new(Brewhouse)
    end
  end

  describe "GET edit" do
    it "assigns the requested brewhouse as @brewhouse" do
      brewhouse = Brewhouse.create! valid_attributes
      get :edit, {:id => brewhouse.to_param}, valid_session
      assigns(:brewhouse).should eq(brewhouse)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Brewhouse" do
        expect {
          post :create, {:brewhouse => valid_attributes}, valid_session
        }.to change(Brewhouse, :count).by(1)
      end

      it "assigns a newly created brewhouse as @brewhouse" do
        post :create, {:brewhouse => valid_attributes}, valid_session
        assigns(:brewhouse).should be_a(Brewhouse)
        assigns(:brewhouse).should be_persisted
      end

      it "redirects to the created brewhouse" do
        post :create, {:brewhouse => valid_attributes}, valid_session
        response.should redirect_to(Brewhouse.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved brewhouse as @brewhouse" do
        # Trigger the behavior that occurs when invalid params are submitted
        Brewhouse.any_instance.stub(:save).and_return(false)
        post :create, {:brewhouse => {}}, valid_session
        assigns(:brewhouse).should be_a_new(Brewhouse)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Brewhouse.any_instance.stub(:save).and_return(false)
        post :create, {:brewhouse => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested brewhouse" do
        brewhouse = Brewhouse.create! valid_attributes
        # Assuming there are no other brewhouses in the database, this
        # specifies that the Brewhouse created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Brewhouse.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => brewhouse.to_param, :brewhouse => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested brewhouse as @brewhouse" do
        brewhouse = Brewhouse.create! valid_attributes
        put :update, {:id => brewhouse.to_param, :brewhouse => valid_attributes}, valid_session
        assigns(:brewhouse).should eq(brewhouse)
      end

      it "redirects to the brewhouse" do
        brewhouse = Brewhouse.create! valid_attributes
        put :update, {:id => brewhouse.to_param, :brewhouse => valid_attributes}, valid_session
        response.should redirect_to(brewhouse)
      end
    end

    describe "with invalid params" do
      it "assigns the brewhouse as @brewhouse" do
        brewhouse = Brewhouse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Brewhouse.any_instance.stub(:save).and_return(false)
        put :update, {:id => brewhouse.to_param, :brewhouse => {}}, valid_session
        assigns(:brewhouse).should eq(brewhouse)
      end

      it "re-renders the 'edit' template" do
        brewhouse = Brewhouse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Brewhouse.any_instance.stub(:save).and_return(false)
        put :update, {:id => brewhouse.to_param, :brewhouse => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested brewhouse" do
      brewhouse = Brewhouse.create! valid_attributes
      expect {
        delete :destroy, {:id => brewhouse.to_param}, valid_session
      }.to change(Brewhouse, :count).by(-1)
    end

    it "redirects to the brewhouses list" do
      brewhouse = Brewhouse.create! valid_attributes
      delete :destroy, {:id => brewhouse.to_param}, valid_session
      response.should redirect_to(brewhouses_url)
    end
  end

end
